piceaTech/ember-rapid-forms

- addon/components/em-text.js
- addon/templates/components/form-group.hbs
- tests/dummy/app/templates/controls/text.hbs
- tests/unit/components/em-text-test.js
Also fixes cols and rows attributes and add basic unit tests for textarea widget
> Add disabled option

- addon/components/em-form-group.js
- addon/components/em-form.js
- addon/mixins/has-property-validation.js
- addon/templates/components/em-form-group.hbs
- addon/templates/components/form-group.hbs
- tests/dummy/app/templates/form.hbs
- tests/unit/components/em-form-group-test.js
- tests/unit/components/em-form-test.js
Adds flags showErrorsOnRender and showErrorsOnFocusIn as discussed on #14.
> Improve errors rendering

- addon/components/em-text.js
- tests/unit/components/em-text-test.js
Modeling the `TextArea` component off of the function `TextInput` component solves this problem.
> Fixed textarea disabled and added passing test

- tests/dummy/app/templates/controls/select.hbs
in reference to issue https://github.com/piceaTech/ember-rapid-forms/issues/59
> updating dummy app to reflect removal of content. prefix on optionValuePath and optionLabelPath

- addon/components/html-select.js
- tests/dummy/app/routes/controls/select.js
- tests/dummy/app/templates/controls/select.hbs
This PR is related to issue #83 
Models are not set on the dummy application but this is for anther PR.
> Set to null if the prompt is selected

- addon/mixins/input-errors.js
- tests/dummy/app/controllers/form-sample.js
- tests/dummy/app/models/simple_person.js
- tests/dummy/app/templates/form_sample.hbs
- tests/dummy/app/templates/getstarted.hbs
> Allow to show or add errors inputs

- addon/components/form-group.js
- addon/mixins/has-property.js
- tests/unit/components/em-checkbox-test.js
- tests/unit/components/em-custom-input-test.js
- tests/unit/components/em-input-test.js
- tests/unit/components/em-select-test.js
- tests/unit/components/em-text-test.js
The important is to have the same value in the id of the input tag and in the for of the label tag.
This fix #88
> Do not duplicate ids

- addon/components/em-form.js
- tests/unit/components/em-form-test.js
This can be useful for actions like : 
```
submit(model) {
model.save();
}
```
> Add the model as an argument of the submission

- addon/components/em-form-control-help.js
- addon/mixins/has-property-validation.js
- addon/mixins/has-property.js
> Replace bindings by aliases

- addon/components/em-form-group.js
- tests/unit/components/em-form-group-test.js
> Make the form group working

- addon/components/em-form-submit.js
- addon/components/em-form.js
- addon/mixins/has-property-validation.js
- tests/unit/components/em-form-submit-test.js
- tests/unit/components/em-form-test.js
Finally, based off of latest master. I closed my old pull request.
This resolves issue #100 .
Josef
> Display validation errors on submit (issue #100)

- ember-cli-build.js
JavaScript's Return Policy on Functions:
- Returns honored once within the current tick without restocking fee.
- Under NO circumstances will a second return be honored.
> Remove unreachable code from ember-cli-build.js

- addon/components/em-form.js
- tests/dummy/app/controllers/form.js
- tests/dummy/app/routes/form.js
- tests/dummy/app/templates/form.hbs
> Use the default form event for submit action

- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/controls/select.hbs
- tests/dummy/app/templates/controls/wrapped-input.hbs
- tests/dummy/app/templates/form.hbs
- tests/dummy/app/templates/getstarted.hbs
- tests/dummy/app/templates/overview.hbs
Hey,
I wanted to share the changes I wanted to make in preparation for the new release.
If you find anything or want to add anything just say it.
> Docs: updating docs to better represent the current usage

- addon/components/em-select.js
- tests/integration/components/em-select-test.js
By default the selected item was not set with there is no prompt which can cause problems when there is no prompts.
> Select first item by default

- addon/components/em-select.js
Sorry but I introduced a bug with rerendering. When it go [here](https://github.com/piceaTech/ember-rapid-forms/compare/master...GCorbel:master#diff-c238abb7d2035c748484d1ac607b3761L87) it created an infinite loop.
> Fix a bug with rerendering

- addon/components/em-select.js
Sorry about that but I had bugs again.
> Fix bugs - Again

- addon/components/em-select.js
- addon/templates/components/em-select.hbs
- tests/dummy/app/controllers/controls/select.js
- tests/dummy/app/templates/controls/select.hbs
- tests/integration/components/em-select-test.js
Hey,
I recreated #76 so we can finally merge it.
Thanks for the effort @bluemari.
Currently it fails. But I don't know why.
> Add support for disabled options in em-select

- addon/components/em-select.js
- addon/templates/components/em-select.hbs
- package-lock.json
- tests/dummy/app/templates/controls/select.hbs
- tests/integration/components/em-select-test.js
As discussed in #177 Remove the need for an extra property. Now content holds the optionGroups.
> Replace optionGroups with content

- index.js
- package-lock.json
- package.json
This hopefully will fix the problem with including ember-font-awesome
> Upgrade ember font awesome to 3.1.0 to fix the include hook

- addon/components/em-select.js
- tests/integration/components/em-select-test.js
> Trigger the action only on change
