piceaTech/ember-rapid-forms

addon/components/html-select.js
tests/unit/components/em-select-test.js

The issue is related to #68 
It allow to do :
{{em-select label="Course" property="course" content=courses canShowErrors=true prompt=" " propertyIsModel=true optionLabelPath="name"}}
`propertyIsModel` allow to assign the model as value.

Allow to return the component itself

---

addon/components/em-form.js

This fixes the "undefined" error logging issue when a call to validate is made.
When internal validations state is false on the form model, and a submit action is called on the form it will produce this error.
Even though the correct behavior should be to allow to submit only when the form is valid (thereby enabling the submit button), it's probably still better to catch this error instead of having it propagate and display in console.
Reference to this issue related to ember-validations can be found here:
https://github.com/dockyard/ember-validations/issues/377

fix undefined error on submit validate

---

addon/components/em-custom-input.js
addon/components/html-custom-input.js
addon/templates/components/em-form-group.hbs
app/components/em-custom-input.js
app/components/erf-html-custom-input.js
tests/dummy/app/templates/controls/wrapped-input.hbs
tests/unit/components/em-custom-input-test.js

This PR allow to do this : 
{{#em-custom-input label="Password" property="password"}}
{{input value=model.password type="password"}}
{{/em-custom-input}}
Useful for complex input like a WYSIWYG editor or a select2 input. It keeps the labels, errors and other options.
The code is not really DRY but I think the whole project needs refactoring. It should be possible to remove `app/components/erf-html-custom-input.js` and `app/components/em-custom-input.js`. This is for another PR.

Add a custom input component

---

addon/templates/components/html-input.hbs
tests/dummy/app/templates/controls/input.hbs
tests/unit/components/em-input-test.js

The attributes were already present on the component class but not assigned on the template file.

Add `required` and `autofocus` attributes to `html-input` component.

---

addon/mixins/input-errors.js
tests/dummy/app/models/simple_person.js
tests/dummy/app/templates/form_sample.hbs
tests/dummy/app/templates/getstarted.hbs

GCorbel's input_errors (https://github.com/piceaTech/ember-rapid-forms/commit/2f3b092da9328de9f4ebd794f42b5aedee4ff96c) added the ability to manually show/hide validation errors. He did this by iterating through eachAttribute and eachRelationship of a DS.Model object and setting the error visibility.
However, computed values that might appear in a form (such as a fullName) are not included in a DS.Model's attributes or relationships. If a validation exists for the computed value, it is listed in the object's dependentValidationKeys.
To show/hide errors for computed values, I've added an iteration through an object's dependentValidationKeys in function changeErrorsVisibility.

Added ability to show/hide errors for computed values

---

addon/components/em-input.js
addon/components/em-text.js
addon/components/html-text.js
addon/templates/components/html-input.hbs
addon/templates/components/html-text.hbs
tests/dummy/app/templates/controls/input.hbs
tests/dummy/app/templates/controls/text.hbs

----
1. 	Update textarea to use native ember helper
+ this literally uses the logic from https://github.com/piceaTech/ember-rapid-forms/commit/24cb1a7c46d21236d81bfe1ff9de6b3e48b1e5b6 to upgrade to ember native component
2.    Add `readonly` attribute to the two now that I know it is missing
3.    Add `autoresize` attribute to solve the original issue: #109 
---

Upgrade <textarea> to ember native component – like {{input}} already does

---

addon/templates/components/html-select.hbs

The value has to be "" for the select to be [considered empty](http://www.w3schools.com/tags/att_select_required.asp).
Also, one has to be able to mark the field as required.

Enable HTML5 required validation on 'em-select' elements

---

addon/components/em-checkbox.js
addon/components/html-checkbox.js
addon/templates/components/control-within-label.hbs
addon/templates/components/html-checkbox.hbs
tests/dummy/app/templates/controls/checkbox.hbs
tests/unit/components/em-form-checkbox-test.js

The following fields are now supported in em-checkbox:
- cid
- elementClass
- disabled (issue #101)
- required
- autofocus
I added tests to match the features. I also updated the documentation in the dummy app to reflect the new properties.
This PR also bundles a fix to label-in-control to support the labelClass attribute.

Updates to em-checkbox (also fixes issue #101)

---

addon/templates/components/html-select.hbs
tests/unit/components/em-select-test.js

It wasn't working as intended after https://github.com/piceaTech/ember-rapid-forms/pull/119/files.
Resulting HTML on the page was `required="mainComponent.required"`, which is obviously not correct.
This fixes it to work as intended.

Fix required on em-select

---

addon/mixins/ember-cp-validations-helper.js
package.json
tests/dummy/app/components/x-sidebar.js
tests/dummy/app/mixins/ember-cp-validations-helper.js
tests/dummy/app/models/person-with-cp-validations.js
tests/dummy/app/router.js
tests/dummy/app/routes/ember-cp-validations.js
tests/dummy/app/templates/ember-cp-validations.hbs
tests/unit/mixins/ember-cp-validations-helper-test.js

As discussed in #139 the currently used solution is no longer supported by their maintainers, that's why I think it is time to finally switch to a supported solution. (Nice Side-effect: we finally can support server-side errors)
In Version 1.0 (hopefully released before the end of this year) we will still be supporting ember-validations and ember-cp-validations (via a mixin)
In Version 2.0 we are gonna drop support for ember-validations. This version is gonna be released by june 2017 (hopefully) 
If anything is unclear or you have a general question feel free to ask.

Switch to using ember-cp-validations

---

addon/components/em-form-group.js

On Ember 2.11, I get this warning on any page which has an `em-form` component: 
"WARNING: Dependent keys containing @each only work one level deep. You used the key "validations.attrs.@each.options.presence.presence" which is invalid. Please create an intermediary computed property."
https://puu.sh/u7wTA/f134d539cd.png
This PR fixes this warning by creating an intermediary computed property, as advised by the warning. No functional changes.

Fix deprecation warning caused by using @each >1 level deep

---

addon/components/em-form-group.js

When an object that utilizes an `Ember.inject.service()` is looked up the  first time, Ember's DI system confirms that the service being injected is actually present and known to the system. If the service is not present it throws an error.
In the use case of this addon, `i18n` is intended to be an optional service and may not be present. If we use `Ember.inject.service()` in this context we loose the ability for it to be optional.
This commit changes things around to avoid using `Ember.inject.service` and instead uses `getOwner(this).lookup('service:i18n')` (which returns `undefined` if the service is not found).

Avoid `Ember.inject.service()` for optional `i18n`

---

addon/components/em-form-group.js
addon/components/html-checkbox.js
addon/components/html-custom-input.js
addon/components/html-input.js
addon/components/html-select.js
addon/components/html-text.js

As of Ember 2.12, arguments to the lifecycle hooks didReceiveAttrs, didInitAttrs, and didUpdateAttrs have been deprecated. https://emberjs.com/blog/2017/03/19/ember-2-12-released.html
Ember Rapid Forms was making use of arguments to the didReceiveAttrs lifecycle hook. This was causing deprecation warnings: https://puu.sh/v99u7/beec39473e.png ("DEPRECATION: [DEPRECATED] Ember will stop passing arguments to component lifecycle hooks. Please change `<repo-name@component:em-input::ember7993>#didReceiveAttrs` to stop taking arguments.")
This PR:
- fixes these deprecation warnings in the method advised by the original RFC for deprecating the arguments: https://github.com/emberjs/rfcs/blob/master/text/0191-deprecate-component-lifecycle-hook-args.md
- removes comments which imply that the …

Fix deprecation warning caused by arguments in didReceiveAttrs

---

addon/mixins/input-component.js

If using Ember >= 2.11, this warning can appear in the console:
"WARNING: Dependent keys containing @each only work one level deep. You used the key "validations.attrs.@each.options.presence.presence" which is invalid. Please create an intermediary computed property." https://puu.sh/vamdd/e97abeb498.png
This has happened here before (https://github.com/piceaTech/ember-rapid-forms/pull/152), so I implemented the same solution.
No functional changes.

Fixed Ember warning caused by using @each > one level deep

---

addon/components/em-checkbox-input.js
addon/components/em-checkbox.js
addon/components/em-form-group.js
addon/mixins/input-component.js
addon/templates/components/em-checkbox-input.hbs
addon/templates/components/em-checkbox.hbs
addon/templates/components/em-form-group.hbs
addon/templates/components/form-group.hbs
app/components/em-checkbox-input.js
tests/dummy/app/templates/controls/checkbox.hbs
tests/integration/components/em-form-checkbox-test.js

Fixes https://github.com/piceaTech/ember-rapid-forms/issues/163.
1. I added a new `labelInControl` flag to indicate that the label is rendered in the control. Seemed to me like the only way to get the label where it needs to be relative to the control in the case of a checkbox. I modified the `input-component` `controlWrapper` property to consider this when determining the bootstrap classes to apply.
2. I didn't remove the `yieldInLabel` handling even though it's not used by anything in this repo anymore, since it could be used by manually rendering a `form-group`.
3. I thought about using `labelWrapperClass` instead of adding `checkboxWrapper`, but then you couldn't use `labelWrapperClass` on a checkbox, so I opted against doing that.
4. I added `class=class` to the `em-checkbox` …

Fix checkbox HTML to match how it used to be rendered

---

addon/components/em-input.js
addon/templates/components/em-input.hbs

This would add `maxlength` attribute, which would allow limiting maximum characters in input element.

Add maxlength attribute to em-input component

---

addon/components/em-select.js

An em-select with a prompt, during its initial (didReceiveAttrs) _setValue call, if the content (options) of the em-select are not yet set but the value of the model's property is not null, the em-select will attempt to set the model's property to null. 
This set operation can cause the backtracking re-render.
The idea with the proposed solution is to cancel the initial _setValue if the content is empty
This may be only one was to cause the issue, and there may be better solutions for it.
This may not even be a problem that is the responsibility of em-select to fix, however my application code doesn't break any conventions I've come across before.
At the very least, I can't see how that addition IF clause will break anything.
Here is a twiddle with an example that is very similar to my …

Possible fix for rare backtracking re-render issue

---

package.json

As stated in #179 one needs ember-font-awesome in the app to have the helper `fa-icon`

fix: move ember-font-awesome to the dependencies

---

addon/components/em-select.js

Assigning a CP is deprecated in 3.2 and, although it shouldn't, it  is causing exceptions in my code:
```TypeError: Cannot set property selectedValue of [object Object] which has only a getter```.
This should get rid of it. I haven't checked thoroughfully if there are similar assignments in the code.

assigning computed properties is deprecated

---

.travis.yml
addon/components/em-select.js
config/ember-try.js

Closes #189
Re-implementation of #190 since that PR isn't being updated
Based on changes requested here #198. PR got closed accidentally while squashing commits.

Fix `run` deprecation, drop 2.8 LTS, add 2.18 LTS

---

addon/components/em-select.js
addon/templates/components/em-select.hbs
package.json
tests/integration/components/em-select-test.js

I noticed that there is no actual code to make multiple selects operate correctly. This is a fairly quick fix to address that.
Unfortunately, it has caused a fair amount of additional complexity:
* Addition of `ember-composable-helpers` to make the `selected` property on the option work.
* Quite of lot of extra code on the component.
Please consider this a starting point, I'm happy to throw this out/make changes if there's a better way. Thanks for the addon!

Bug fix: make multiple selects work properly
